import type { Standard } from "@/types/standard";
import { dummyFolderTree } from "./forge-dummy";

export const dummyStandards: Standard[] = [
  {
    id: "std-nextjs-clean-1",
    name: "My Next.js Clean Standard",
    framework: "nextjs",
    description: "App Router, src/features, Zustand, Tailwind, kebab-case. The gold standard for vibe coding.",
    folderStructure: dummyFolderTree,
    globalRules: {
      namingConvention: "kebab-case",
      stateManagement: "Zustand",
      styling: "Tailwind v4 + shadcn/ui",
      principles: ["Feature-based", "Clean Architecture", "No cross-feature imports"],
    },
    mcpStatus: "active",
    mcpEndpoint: "https://cleanforge.run.app/mcp/user-1/std-nextjs-clean-1/sse",
    mcpToken: "mcp_tok_abc123xyz",
    createdAt: "2026-08-30T10:00:00Z",
    updatedAt: "2026-09-02T14:30:00Z",
  },
  {
    id: "std-ecommerce-modular",
    name: "E-Commerce Modular",
    framework: "nextjs",
    description: "Modular monolith for e-commerce. Features: cart, payment, inventory.",
    folderStructure: dummyFolderTree,
    globalRules: {
      namingConvention: "kebab-case",
      stateManagement: "TanStack Query + Zustand",
      styling: "Tailwind v4",
      principles: ["Modular", "Domain-driven"],
    },
    mcpStatus: "active",
    mcpEndpoint: "https://cleanforge.run.app/mcp/user-1/std-ecommerce-modular/sse",
    mcpToken: "mcp_tok_ecom456",
    createdAt: "2026-08-28T09:00:00Z",
    updatedAt: "2026-09-01T11:00:00Z",
  },
  {
    id: "std-nestjs-modular",
    name: "NestJS Modular API",
    framework: "nestjs",
    description: "NestJS with modules, clean architecture, Prisma ORM.",
    folderStructure: dummyFolderTree,
    globalRules: {
      namingConvention: "kebab-case",
      stateManagement: "N/A (Backend)",
      styling: "N/A",
      principles: ["Modular", "Clean Arch"],
    },
    mcpStatus: "inactive",
    mcpEndpoint: "https://cleanforge.run.app/mcp/user-1/std-nestjs-modular/sse",
    mcpToken: "mcp_tok_nest789",
    createdAt: "2026-08-25T08:00:00Z",
    updatedAt: "2026-08-30T16:00:00Z",
  },
  {
    id: "std-go-clean",
    name: "Go Clean Architecture",
    framework: "go",
    description: "Go with internal/domain, use-case, handler layers.",
    folderStructure: dummyFolderTree,
    globalRules: {
      namingConvention: "kebab-case",
      stateManagement: "N/A",
      styling: "N/A",
      principles: ["Hexagonal", "Dependency Inversion"],
    },
    mcpStatus: "draft",
    mcpEndpoint: "https://cleanforge.run.app/mcp/user-1/std-go-clean/sse",
    mcpToken: "mcp_tok_go101",
    createdAt: "2026-08-20T07:00:00Z",
    updatedAt: "2026-08-29T09:00:00Z",
  },
  {
    id: "std-saas-starter",
    name: "SaaS Starter Kit",
    framework: "nextjs",
    description: "SaaS boilerplate with auth, billing, dashboard.",
    folderStructure: dummyFolderTree,
    globalRules: {
      namingConvention: "kebab-case",
      stateManagement: "Zustand",
      styling: "Tailwind + shadcn",
      principles: ["Feature-based", "Multi-tenant"],
    },
    mcpStatus: "active",
    mcpEndpoint: "https://cleanforge.run.app/mcp/user-1/std-saas-starter/sse",
    mcpToken: "mcp_tok_saas202",
    createdAt: "2026-08-22T10:00:00Z",
    updatedAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "std-laravel-modular",
    name: "Laravel Modular",
    framework: "nestjs",
    description: "Laravel modular structure for large apps.",
    folderStructure: dummyFolderTree,
    globalRules: {
      namingConvention: "kebab-case",
      stateManagement: "N/A",
      styling: "Blade + Tailwind",
      principles: ["Modular", "Service Layer"],
    },
    mcpStatus: "draft",
    mcpEndpoint: "https://cleanforge.run.app/mcp/user-1/std-laravel-modular/sse",
    mcpToken: "mcp_tok_lara303",
    createdAt: "2026-08-18T10:00:00Z",
    updatedAt: "2026-08-28T10:00:00Z",
  },
];
